/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   Pages.cpp                                          :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: del-yaag <del-yaag@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/03/31 02:29:23 by amoukhle          #+#    #+#             */
/*   Updated: 2024/03/31 12:03:02 by del-yaag         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "Script.hpp"

std::string LoginPage( void ) {
    std::string html_code = "<!DOCTYPE html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "    <meta charset=\"UTF-8\">\n"
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "    <title>Login</title>\n"
        "    <style>\n"
        "        body {\n"
        "            font-family: Arial, sans-serif;\n"
        "            margin: 0;\n"
        "            padding: 0;\n"
        "            display: flex;\n"
        "            justify-content: center;\n"
        "            align-items: center;\n"
        "            height: 100vh;\n"
        "            background-color: #f5f5f5;\n"
        "        }\n"
        "\n"
        "        .login-container {\n"
        "            background-color: #fff;\n"
        "            padding: 20px;\n"
        "            border-radius: 5px;\n"
        "            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\n"
        "        }\n"
        "\n"
        "        h2 {\n"
        "            text-align: center;\n"
        "            margin-bottom: 20px;\n"
        "        }\n"
        "\n"
        "        .input-group {\n"
        "            margin-bottom: 15px;\n"
        "        }\n"
        "\n"
        "        label {\n"
        "            display: block;\n"
        "            margin-bottom: 5px;\n"
        "        }\n"
        "\n"
        "        input[type=\"text\"],\n"
        "        input[type=\"password\"] {\n"
        "            width: 100%;\n"
        "            padding: 10px;\n"
        "            border: 1px solid #ccc;\n"
        "            border-radius: 3px;\n"
        "        }\n"
        "\n"
        "        button {\n"
        "            width: 100%;\n"
        "            padding: 10px;\n"
        "            background-color: #007bff;\n"
        "            color: #fff;\n"
        "            border: none;\n"
        "            border-radius: 3px;\n"
        "            cursor: pointer;\n"
        "        }\n"
        "\n"
        "        button:hover {\n"
        "            background-color: #0056b3;\n"
        "        }\n"
        "    </style>\n"
        "</head>\n"
        "<body>\n"
        "    <div class=\"login-container\">\n"
        "        <h2>Login</h2>\n"
        "        <form action=\"/a.out\" method=\"post\" enctype=\"multipart/form-data\">\n"
        "            <div class=\"input-group\">\n"
        "                <label for=\"username\">Username:</label>\n"
        "                <input type=\"text\" id=\"login\" name=\"login\" required>\n"
        "            </div>\n"
        "            <div class=\"input-group\">\n"
        "                <label for=\"password\">Password:</label>\n"
        "                <input type=\"password\" id=\"password\" name=\"password\" required>\n"
        "            </div>\n"
        "            <button type=\"submit\">Login</button>\n"
        "        </form>\n"
        "    </div>\n"
        "</body>\n"
        "</html>";
	return (html_code);
}

std::string welcomePage( std::string login ) {
	std::string welcome_page = "<!DOCTYPE html>\n"
		"<html lang=\"en\">\n"
		"<head>\n"
		"    <meta charset=\"UTF-8\">\n"
		"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
		"    <title>Welcome</title>\n"
		"    <style>\n"
		"        body {\n"
		"            font-family: Arial, sans-serif;\n"
		"            margin: 0;\n"
		"            padding: 0;\n"
		"            display: flex;\n"
		"            justify-content: center;\n"
		"            align-items: center;\n"
		"            height: 100vh;\n"
		"            background-color: #f5f5f5;\n"
		"        }\n"
		"\n"
		"        .welcome-container {\n"
		"            text-align: center;\n"
		"        }\n"
		"\n"
		"        h1 {\n"
		"            font-size: 2rem;\n"
		"            color: #007bff;\n"
		"            margin-bottom: 20px;\n"
		"        }\n"
		"\n"
		"        p {\n"
		"            font-size: 1.2rem;\n"
		"            margin-bottom: 20px;\n"
		"        }\n"
		"\n"
		"        form {\n"
		"            margin-top: 20px;\n"
		"        }\n"
		"\n"
		"        input[type=\"text\"] {\n"
		"            padding: 5px;\n"
		"            width: 200px;\n"
		"        }\n"
		"\n"
		"        input[type=\"submit\"] {\n"
		"            padding: 5px 10px;\n"
		"            background-color: #007bff;\n"
		"            color: #fff;\n"
		"            border: none;\n"
		"            border-radius: 3px;\n"
		"            cursor: pointer;\n"
		"        }\n"
		"\n"
		"        input[type=\"submit\"]:hover {\n"
		"            background-color: #0056b3;\n"
		"        }\n"
		"    </style>\n"
		"</head>\n"
		"<body>\n"
		"    <div class=\"welcome-container\">\n"
		"        <h1>Welcome, " + login + "! </h1>\n"
		"        <p>You have successfully logged in.</p>\n"
		"    </div>\n"
		"</body>\n"
		"</html>";
	return (welcome_page);
}

std::string errorPage() {
	std::string error_page = "<!DOCTYPE html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "    <meta charset=\"UTF-8\">\n"
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "    <title>Error Page</title>\n"
        "</head>\n"
        "<body>\n"
        "    <div style=\"text-align: center; margin-top: 20%;\">\n"
        "        <h1>404 - Not Found</h1>\n"
        "        <p>The requested page could not be found.</p>\n"
        "        <p><a href=\"/\">Go to Home Page</a></p>\n"
        "    </div>\n"
        "</body>\n"
        "</html>";
	return (error_page);
}